<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Domain.Identity\Domain.Identity.csproj"/>
        <ProjectReference Include="..\Domain\Domain.csproj"/>
        <ProjectReference Include="..\Port.Driven\Port.Driven.csproj"/>
        <ProjectReference Include="..\Port.Driving\Port.Driving.csproj"/>
    </ItemGroup>

</Project>
