<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Binders\" />
      <Folder Include="CommandHandlers\" />
      <Folder Include="Commands\" />
      <Folder Include="Exceptions\" />
      <Folder Include="Interfaces\" />
      <Folder Include="Policies\Identities\" />
      <Folder Include="Queries\" />
      <Folder Include="Profiles\" />
      <Folder Include="QueryHandlers\" />
      <Folder Include="Services\" />
      <Folder Include="Validators\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Adapter\Adapter.csproj" />
      <ProjectReference Include="..\Shared\Shared.csproj" />
      <ProjectReference Include="..\Contracts\Contracts.csproj" />
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="13.0.1" />
      <PackageReference Include="FluentValidation" Version="11.11.0" />
    </ItemGroup>

</Project>
