<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Domain.Identity\Domain.Identity.csproj"/>
        <ProjectReference Include="..\Domain.Core\Domain.Core.csproj"/>
        <ProjectReference Include="..\Port.Driven.EFCore\Port.Driven.EFCore.csproj"/>
        <ProjectReference Include="..\Port.Driven.NHibernate\Port.Driven.NHibernate.csproj"/>
        <ProjectReference Include="..\Port.Driven.Shared\Port.Driven.Shared.csproj"/>
        <ProjectReference Include="..\Port.Driving.Shared\Port.Driving.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Commands\V1\CreateCommands\"/>
        <Folder Include="DPOs\"/>
    </ItemGroup>

</Project>
