<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="Views\Shared\_Header.cshtml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Views\Shared\_Header.cshtml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.20" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Adapter.Driven.EFCore\Adapter.Driven.EFCore.csproj" />
    <ProjectReference Include="..\Adapter.Driven.NHibernate\Adapter.Driven.NHibernate.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="Areas\Customer\Data\" />
    <Folder Include="Areas\Customer\Models\" />
    <Folder Include="Areas\Host\Data\" />
    <Folder Include="Areas\Host\Models\" />
  </ItemGroup>
</Project>
