<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Data\Seeding\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Adapter.EFCore\Adapter.EFCore.csproj" />
        <ProjectReference Include="..\Adapter.MediatR\Adapter.MediatR.csproj" />
        <ProjectReference Include="..\Port.Driven\Port.Driven.csproj"/>
    </ItemGroup>

</Project>
