<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.20" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="7.0.20" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.20">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="6.0.36" />
      <PackageReference Include="NLog.Database" Version="6.0.2" />
      <PackageReference Include="NLog.Web.AspNetCore" Version="6.0.2" />
      <PackageReference Include="Oracle.EntityFrameworkCore" Version="7.21.13" />
      <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
      <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
      <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
      <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Auditing\" />
      <Folder Include="Binders\" />
      <Folder Include="Caching\" />
      <Folder Include="ExternalIntergations\" />
      <Folder Include="Persistence\EntitiesConfig\" />
      <Folder Include="Persistence\Migrations\" />
      <Folder Include="Persistence\Repositories\" />
      <Folder Include="Exceptions\" />
      <Folder Include="Logging\" />
      <Folder Include="Persistence\Seeding\" />
      <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Adapter\Adapter.csproj" />
      <ProjectReference Include="..\Domain\Domain.csproj" />
      <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

</Project>
