<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.36"/>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.18"/>
        <PackageReference Include="Scrutor" Version="4.2.2"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Adapter.Driven.EFCore\Adapter.Driven.EFCore.csproj"/>
        <ProjectReference Include="..\Adapter.Driven.MediatR\Adapter.Driven.MediatR.csproj"/>
        <ProjectReference Include="..\Adapter.Driven.NHibernate\Adapter.Driven.NHibernate.csproj"/>
    </ItemGroup>

</Project>
